version: '3.8'
services:
  server:
    restart: always
    build: .
    volumes:
      - .:/app
      - /app/node_modules  # Don't sync this folder to host machine
      - /app/build         # Don't sync this folder to host machine
    ports:
      - '8080:8080'
    depends_on:
      - database
  database:
    image: library/postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: database
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: